export const Actions = {
    SET_TRACKS: 'SET_TRACKS',
    SET_TRACKS_TITLE: 'SET_TRACKS_TITLE',
    SET_ALL_TRACKS: 'SET_ALL_TRACKS',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    PLAYING_TRACK_ID: 'PLAYING_TRACK_ID',
    ADD_PLAYLIST: 'ADD_PLAYLIST',
    DELETE_PLAYLIST: 'DELETE_PLAYLIST',
    ADD_TRACK_TO_PLAYLIST: 'ADD_TRACK_TO_PLAYLIST',
    DELETE_TRACK_FROM_PLAYLIST: 'DELETE_TRACK_FROM_PLAYLIST',
}